superuser: null
# commented until <walletAmount> gets a class getter
welcomeMessage:
   <bold><yellow>Welcome to AltQuest, the server that runs on Altcoin! ^_^<reset>

   <yellow>Your AltQuest BTC address is <green><walletAddress>
   <yellow>Your balance is <green><walletAmount> SAT
